events {}

http {
    upstream spring-server {
        server spring-app:8080;  # Spring Boot 컨테이너
    }

    # HTTP 요청을 HTTPS로 강제 리디렉션 (ALB에서 직접 HTTP 요청을 허용하는 경우)
    server {
        listen 80;
        server_name farmon-be.site;

        # ALB Health Check를 위한 예외 처리
        location /actuator/health {
            proxy_pass http://spring-server;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # HTTP 요청을 HTTPS로 리디렉션
        return 301 https://$host$request_uri;
    }

    # 실제 요청을 처리하는 서버 블록
    server {
        listen 80;
        server_name farmon-be.site;

        location / {
            proxy_pass http://spring-server;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # WebSocket 요청 처리
        location /ws-stomp {
            proxy_pass http://spring-server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
